---
name: Build an image

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    inputs:
      image:
        description: 'Target image(s)'
        default: 'keystone'
        required: true
      release:
        description: 'Target release'
        default: 'yoga'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: stable/${{ github.event.inputs.release }}

    - name: Set up Python
      uses: actions/setup-python@v2.2.1
      with:
        python-version: 3.9

    - name: Install requirements
      run: pip install -r requirements.txt

    - name: Build target image(s)
      run: python tools/build.py -b ubuntu ${{ github.event.inputs.image }} --registry ghcr.io/eschercloudai --tag ${{ github.event.inputs.release }}-$(git rev-parse --short HEAD)
